# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(default=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'), verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('place_detail', models.CharField(default='', max_length=400, verbose_name='详细信息')),
                ('lat', models.CharField(default='', max_length=50, verbose_name='纬度')),
                ('lon', models.CharField(default='', max_length=50, verbose_name='经度')),
            ],
            options={
                'ordering': ['start_time'],
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('sub_title', models.CharField(default='', max_length=200, verbose_name='子标题')),
                ('intro', models.TextField(default='', verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新时间')),
                ('arrival_time', models.DateTimeField(default=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'), verbose_name='到达时间')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('detail', models.CharField(default='', max_length=400, verbose_name='详细信息')),
                ('lat', models.CharField(default='', max_length=50, verbose_name='纬度')),
                ('lon', models.CharField(default='', max_length=50, verbose_name='经度')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-arrival_time'],
                'db_table': 'station',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='station',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itinerary.Station'),
        ),
    ]
