# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新时间'),
        ),
    ]
