# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_event_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='station',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到达时间'),
        ),
    ]
