# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_auto_20160817_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_detail',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='station',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='经度'),
        ),
    ]
