# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20160817_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place_detail',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='地址详细信息'),
        ),
        migrations.AlterField(
            model_name='station',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
