# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_auto_20160817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
